### PR TITLE
Ensure Consensus on Future String Changes

### PR DESCRIPTION
**Pull request by sr093906**
@nhirokinet  I asked for string changes made to English and Japanese strings to apply to Chinese one in https://github.com/nhirokinet/bluelineconsole/pull/56, And based on my understanding, I think you agreed to such change.

But the two string changes happened last night Beijing Time shows no change to Chinese strings.xml still.  I think there are two possibilities. 

https://github.com/nhirokinet/bluelineconsole/compare/nhirokinet:c609524...nhirokinet:16e7d29 
https://github.com/nhirokinet/bluelineconsole/compare/nhirokinet:16e7d29...nhirokinet:4549910

First, you forget making changes to Chinese. If so, I kindly ask you committing such changes next time. If you confuse what the changes should look like. Please look at file changes in this pull request. I personally believe this is the reason. 

Second, making such change is reluctant to you . If this is the thing, whatever the reason. Just tell me clearly. I know what to do next.

### CODE REVIEW

**Comment by nhirokinet** [comment]
There seems to be some misunderstanding.

I recognized that the problem was that I rearranged existing lines, many times little by little, and diff was complicated to you. That is why I wrote `when I change previous lines` in the previous comment. Also under this recognition I did not make any change to Chinese string yesterday just because no previous lines were changed. Maybe this recognition was not correct.

So now what is your expectation?

1. If you expect adding English text to Chinese file like this pull request when English was changed, that's fine, I can just not ignore IDE warning. And this is OK if you confirm:
    - you feel comfortable I add English text to Chinese file
    - you don't rely on highlights on untranslated texts in Android Studio or similar tool at all.

2. Or maybe adding commented out tag like below would make less problem than 1?
```xml
    <!-- string name="id_for_string">English text</string -->
```

3. If you expect adding tag with empty text, that is not acceptable because build of that file would display nothing (not even original English) on Chinese terminal on corresponding area.

If none of above is your expectation then can you clarify that?

**Comment by sr093906** [comment]
@nhirokinet Thanks for the explanation above. I prefer option 1. Please add English text to Chinese file like this pull request when English was changed.

**Comment by sr093906** [comment]
And please keep this pull request open until I made changes to untranslated lines.

**Comment by nhirokinet** [comment]
@sr093906 OK thank you for clarification. Currently I think there is no problem for option 1, but just in case if I found some technical problem about option1, how do you feel about option 2?

**Comment by nhirokinet** [comment]
(imaging technical problem like some accessibility or any other system works wrongly if language is different than declared)

**Comment by sr093906** [comment]
@nhirokinet In this case, please notify me first.  I personally think it is not very possible without substantial changes to whole structure or you decided to write it in a different language. Thanks for that.

**Comment by nhirokinet** [comment]
@sr093906 Yes at least I will let you know in comment, so that you have a space to discuss about change, and (even if after first pushing to master) I can rearrange and adapt the flow of translation. But this is just in case, currently I don't expect to happen.

**Comment by sr093906** [comment]
@nhirokinet Finished translation. Sorry for the delay.

**Comment by nhirokinet** [comment]
@sr093906 Thank you for every time! No problem for delay.
I'm now working on some minor issues and behaviors, but it is expected to resolve. If (and I wish) I don't find new difficult bugs, version 1.1.0 will be released soon.

**Comment by sr093906** [comment]
@nhirokinet Good to know !

**Pull request merged**
