### PR TITLE
Update Chinese Strings

### PR DESCRIPTION
**Pull request by sr093906**

### CODE REVIEW

**Comment by nhirokinet** [comment]
Thank you!

**Comment by nhirokinet** [comment]
Corresponding change is intended to improve compatibility with IMEs other than Japanese.
In my testing environment Chinese Gboard also seemed to have problem that Chinese cannot be input, but I think this will be fixed in next release (and can obtain current behavior is in options).

**Comment by sr093906** [comment]
@sr093906 Ok, good to know.

**Comment by sr093906** [comment]
@nhirokinet Ok, good to know that.

**Pull request merged**
