### PR TITLE
No need to add files like in en-US

### PR DESCRIPTION
**Pull request by Artem13327**

### CODE REVIEW

**Comment by nhirokinet** [comment]
Screenshots are taken with each language setting, and the screen slightly differs.

For icons, is there any problem by duplicated copies? There files are not included to built app.

Fastlane files are for F-Droid to read parse, I'm not sure to delete because I cannot try without affecting actual content, do you have some specific documentation?

**Comment by IzzySoft** [comment]
`en-US` is used for all elements missing in other languages (aka "Fallback solution"). Giving examples based on the assumptions I have `de-DE` configured on my device:

* if `de-DE` as well as `de` are entirely absent from your Fastlane, everything is used from `en-US`
* if one of the two is present but lacking screenshots altogether, screenshots are taken from `en-US` (but that will **NOT** happen if even a single screenshot is present)
* if `full_description` is missing in both `de[-DE]`, that is taken from `en-US`
* and so on

So no need to duplicate **identical** content, like the icon. It won't break anything, but it wastes space (and bandwidth) unnecessarily.

**Comment by nhirokinet** [comment]
Looks like this docs says so, and maybe for future reference I should see this. I would take care on next update about this.

https://github.com/fastlane/fastlane/blob/2.28.7/supply/README.md#images-and-screenshots

But anyway, Japanese screenshots are not identical, at least they cannot be deleted.

**Comment by IzzySoft** [comment]
> Looks like this docs says so

That Readme doesn't go to that depth. It just tells you where things end up. But believe me as a maintainer of multiple F-Droid repositories for many years, that's the way it is: `en-US` is used as fall-back for everything not existing in a different locale. Else you'd need to set up all locales possibly in existence or they would see nothing, right? :wink:

> Japanese screenshots are not identical, at least they cannot be deleted.

That's perfectly true: what's different needs to be there. But no need to duplicate the very same screenshots from `en-US` to, say, Spanish; if there are no screenshots in `es` nor `es-ES`, a device configured to Spanish would still see the ones from `en-US`.

**Comment by nhirokinet** [comment]
@Artem13327 Can you restore Japanese images which are not identical to the ones in English, or can you describe the reason you still do not want to restore if any? At least this pull request cannot be merged unless this problem is solved (commented above).

**Comment by nhirokinet** [comment]
@Artem13327 How about the comment above?

**Comment by nhirokinet** [comment]
Could not get respond about my question for more than a month, but at least I understood it is better to remove 2 of 5 files you suggested. I applied this as #283 and then closing this pull request.

**Pull request closed without merging**
