### PR TITLE
upgrade calculator

### PR DESCRIPTION
**Pull request by tumuyan**
import MVEL2 to upgrade calculator, for example input these:
1. a=1;b=2;a+b
2. Math.sin(2)
3. def circ(a,b) { return 2*a+2*b;} circ(3,4)

Also I define 2 random function in calculator:
1. rand()  // a random float between 0 and 1
2. randint(a) //  a random int between 1 and a

### CODE REVIEW

**Comment by nhirokinet** [comment]
I'll take a look at MVEL, as once added this, changing the syntax will be difficult in the future.

I'm also worrying that this code will make calculator run in two methods by default. If the slightest change in formula makes unexpected difference that is not good.

So please let me have a time to take a look.

license-checker is handwritten program that is on `ci` directory. This not only checks license but checks software lists to make sure all dependencies are checked and written on license screen, so license-checker.py should be modified to fix it. Also this means "licensing_notice_body" in app/src/main/res/values/strings.xml should be modified.

**Comment by nhirokinet** [comment]
Took some look at MVEL document, this seems to support loop with arbitrary length. This means query may take a long time or even never finishes.

So this must not be run in main thread. Also, even if the thread is split, app cannot determine the result length forever in that situation.

In addition to the problem of compatibility and mixing some different system in one calculator commented above, controlling a loop may have a problem.

Enriching calculator itself may be a desired function, but I feel this approach makes a lot of problem and the approach should be more controllable.

**Comment by tumuyan** [comment]
> Took some look at MVEL document, this seems to support loop with arbitrary length. This means query may take a long time or even never finishes.
> 
> So this must not be run in main thread. Also, even if the thread is split, app cannot determine the result length forever in that situation.

remove it to a new thread and set timeout  should be able to avoid this problem

**Comment by nhirokinet** [comment]
As a non-default option, running slow calculation and timeout can be one solution for UI to be displayed correctly. But I'm not sure the calculation process can be finished while loop and stop CPU usage still.

And there is still a problem of mixing multiple calculator logics. To be honest I'm not currently so much willing to accept MVEL style program input.

**Comment by nhirokinet** [comment]
If current calculator is simply lower compatible of MVEL, situation might be different. But current calculator supports unit conversion, float error detection and no error calculation in the situations like `1/3+1/6`, and adding MVEL as updates seems to conflict to current program...

**Comment by tumuyan** [comment]
The  current calculator supports unit conversion, float error detection and no error calculation, but there is no random, power, sin and others function.
So the Mvel only eval when the current calculator could not get result.
Or we can use Regular expression filtering `for`  `while`  to avoid long time operation?

**Comment by nhirokinet** [comment]
> The current calculator supports unit conversion, float error detection and no error calculation, but there is no random, power, sin and others function.

Yes, there are a lot of functions current calculator does not support. But as this is not a severe bug, this does not justify well the problems occurs by adding other function. And the problem occurs by the method selected for this purpose, not the purpose itself (although adding some functions itself leads a problem; `3^2` should be 9 (power) or 1(xor), what happens if `3km^2` (like this in future situation), and so on...)

> So the Mvel only eval when the current calculator could not get result.

Yes, I know it is "compatible"

But new code means that 

```
1m + 1km
```
-> works

```
2+3; 4+5
```
-> works

```
1m + 1km; 2m + 2km
```
-> syntax error

And same for other features or even more slight behaviors. I think this is strange and confusing for users.

> We can use regular expression filtering for while to avoid long time operation? Or filtering { ?

This, including current regular expression for random, is trying to interfere what is implemented in MVEL from outside. This has some problems.

- Dropping good point of using external complete library, I have to understand the syntax precisely.
- Code will be messy for managing what happens in each situation
- Filtering `for` or `while` to avoid long time operation, in other word implementing denylist, not allowlist.to preserve correct behavior, means we have to know all of the words available in MVEL. It's not practical to manage complete list that keeps the program working properly.

**Comment by tumuyan** [comment]
Good examples. `^` in MCEL syntax is different from normal math syntax. I don't have a clear idea about this.

> And same for other features or even more slight behaviors. I think this is strange and confusing for users.  

You are right.  I have some ideas, but couldn't solve these problems perfectly. Maybe only wolframalpha could  work perfectly.  
How about tip the user that only `+-*/` operations are supported for unit conversions, and MVEL syntax does not support xxxxx.(Maybe only `while | untile | for` might  take long time,  confirmation needed) Otherwise MVEL should not be import.

Maybe only wolframalpha could  work perfectly, but its API is limited
image

image

(Also has some problem)
image

**Comment by nhirokinet** [comment]
> How about tip the user that only +-*/ operations are supported for unit conversions, and MVEL syntax does not support xxxxx.

I think rather than this workaround it should be implemented as completely separate app...

**Pull request closed without merging**
