### PR TITLE
Add: Qwant, MetaGer and Swisscows search engines closes #11

### LINKED ISSUE #11: [Feature Request] Add the privacy oriented search engines (MetaGer, Qwant, Searx)
I think the title explains it most clearly.

### PR DESCRIPTION
**Pull request by machiav3lli**

### CODE REVIEW

**Comment by nhirokinet** [comment]
MetaGar and Swisscows seem to identify language by URL, so I think output URL should be changed by device locale setting, like other engines in the file.

**Comment by machiav3lli** [comment]
I've chosen the main(english) instance for MetaGer as it has only three (en, de, sp) while swisscow uses the device's region to identify relevant search results (while it supports mainly european languages)

**Comment by nhirokinet** [comment]
For Swisscow, I see, it seems to follow Accept-Language.
For MetaGer, even if device locale is set to German or Spanish this URL shows English page. Other search engines links on Blue Line Console is set to show the link that matches the device preference as much as possible, so this behavior should be consistent in the app.

**Comment by machiav3lli** [comment]
MetaGer has different domain for each language: .org, .de and .es. This is why it doesn't change it automaticly.
Sorry I didn't put all of this information in the last comment, as I've seen it as non-relevant.

**Comment by nhirokinet** [comment]
In current code, Yahoo search and Wikipedia also have different domains for each country or language, and in this app I decided to obey the device setting.

**Comment by nhirokinet** [comment]
Inconsistency of language choice in one class is not resolved yet, and now custom URLs can be added from GUI in 1.0.9 or later.
Adding search engines may be done in some reasons later, but for this pull request I will close it.

**Pull request closed without merging**
