### PR TITLE
Added icon show/hide functionality

### PR DESCRIPTION
**Pull request by AtaYalcin**
I used google translate for the non english "Show icons" texts. They might be erronous.

### CODE REVIEW

**Review by nhirokinet — COMMENTED** [review]
> I used google translate for the non english "Show icons" texts.

Please do not this unless you checked that Google translate is accepted by code owner's policy.

This will have both license or legal problem and quality problem.

I couldn't find a good document in English, but the link below explains what happened to Ubuntu Japanese translate community. I think you can understand what it says with Google translate.
https://blog.goo.ne.jp/ikunya/e/37e5a52e10ab26fcbd4f7ff867e9eace

For Android strings files, if there is no corresponding Japanese text, it will fall back to the default string (English here). So you can just update string.xml for English and keep files for other languages unchanged. For this repository there is a case I place English text for non-English files, but you don't have to do so and you should just update English file. Translators (if there are ones willing to translate) will add translation separately.

I am Japanese, so after merging this pull request I can add Japanese translation myself.

**Comment by AtaYalcin** [comment]
Sorry for the silly mistakes and wrong practices , i am quite new to android programming and github :)) . I did the changes you requested.

**Review by nhirokinet — APPROVED** [review]

**Comment by nhirokinet** [comment]
Closes #257

**Comment by nhirokinet** [comment]
Thanks!

**Pull request merged**
